openhantek/src/openhantek.cpp
openhantek/src/settings.cpp

When run on Ubuntu OpenHantek has some strange behaviour around the widgets, panels and labels on the scope view.[0]
At start up those parts of the UI will be in floating, undocked mode and sometimes simultaneously docked. Resizing the window will move the floating parts move with the edges of the window, but moving the window has no effect on them. 
I do not know if this is a bug in OpenHantek, in QT, or someplace else. I did however find that setting floating explicitly will make the issue go away.[1]
Note:
This patch also removes enabling CH1 by default as this seems to have some weird interaction at a point I have not been able to locate.
If 'used' is not set to false, the labels on the scope view will continue to float in separate windows.
Always setting it to false will actually …

Removes floating doubles of widgets and panels.

---

openhantek-extractfw/INSTALL

It's impossible for a newcomer to build extractfw basing on current instructions.

Fix installation instructions

---

.travis.yml

This was introduced in 5074707. Since then travis fails to build; it
says "missing config".[1]
Unfortunately the travis validation at http://lint.travis-ci.org/
is out of date; it doesn't even know about the "file" option, nor
"addons", "notifications", etc.
So I tested this by trial and error.
According to the comment on this stackoverflow answer[2] the "file_glob"
option existed at some point but now has been removed, and it is
implied.
I've also removed "branch: master" to avoid confusion, because "tags:
true" (added in 5074707) causes the "branch" condition to be
ignored.[3]
[1]: https://travis-ci.org/OpenHantek/openhantek/requests
[2]: http://stackoverflow.com/a/28579635/606705
[3]: https://docs.travis-ci.com/user/deployment/#Conditional-Releases-with-on%3A

Fix travis build by removing unknown "file_glob" option

---

readme.md

cmake gave the following error when using the instructions given in the readme:
CMake Error at openhantek/CMakeLists.txt:3 (find_package):
By not providing "FindQt5Widgets.cmake" in CMAKE_MODULE_PATH this project
has asked CMake to find a package configuration file provided by
"Qt5Widgets", but CMake did not find one.
Could not find a package configuration file provided by "Qt5Widgets" with
any of the following names:
Qt5WidgetsConfig.cmake
qt5widgets-config.cmake
Add the installation prefix of "Qt5Widgets" to CMAKE_PREFIX_PATH or set
"Qt5Widgets_DIR" to a directory containing one of the above files.  If
"Qt5Widgets" provides a separate development package or SDK, be sure it has
been installed.
-- Configuring incomplete, errors occurred!
This happens because cmake does not have …

Update readme.rd info for OSX in cmake

---

openhantek/src/configdialog.cpp
openhantek/src/configpages.cpp
openhantek/src/configpages.h
openhantek/src/exporter.cpp
openhantek/src/hantek/control.cpp
openhantek/src/helper.h
openhantek/src/settings.cpp

1) Enable user to choose screen & print colors separately (option already supported by **DsoSettingsView.color**). 
2) Enabled "Export Images with Screen Colors" checkbox in "Files" dialog.
3) Couple of minor enhancements: fixed width of icons panel in Settings, suppress printing spectrum magnitude if spectrum is not printed.
4) Bugfixes:
Eliminated compile time warnings:
```
...helper.h:111:2: warning: extra ‘;’ [-Wpedantic]
};
^
...control.cpp: In member function ‘unsigned int Hantek::Control::updateSamplerate(unsigned int, bool)’:
...control.cpp:724:26: warning: overflow in implicit constant conversion [-Woverflow]
downsamplerValue = 0xffff;
^
```

Color config dialog change + minor bugfixes

---

openhantek/src/dataanalyzer.cpp
openhantek/src/exporter.cpp
openhantek/src/hantek/control.cpp

1) CSV export into long lines looks pretty useless, e.g. they make LibreOffice Calc fail with message "The data could not be loaded completely because the maximum number of columns per sheet was exceeded". Changed CSV export to columns. X-axis (time/frequency) values are printed in each line, thus making import into plot tools easier.
2) Fixed bug in MATH channel (double-increment of iterator), changed postfix iterator increments to prefix increments.
3) Improved DSO6022BE Software trigger stability by increasing dropped sample count to 1040 (0x410). Most likely the same buffer truncation needs to be applied to 6022BL. Still have to dive into jhoenicke's firmware, fast sample rates might require different approach to data acquisition.

CSV export in columns, math channel iterator fix

---

readme.md

Without this package, I ran into the following error:
```
~/openhantek/build master $ cmake ..
-- The C compiler identification is GNU 7.2.0
-- The CXX compiler identification is GNU 7.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
ma-- Detecting CXX compile features - done
CMake Error at openhantek/CMakeLists.txt:5 (find_package):
By not providing "FindQt5OpenGL.cmake" in …
```

readme: add missing libqt5opengl5-dev

---

.gitignore
CMakeLists.txt
openhantek/src/dockwindows.cpp
openhantek/src/dockwindows.h
openhantek/src/hantek/control.cpp
openhantek/src/openhantek.cpp

1) Improved 6022BE SW trigger stability & waveform display by further reducing record length down to 8KS, drop 1K+16 samples from the head and 1K-16 from the tail.
2) Removed 32KS record length option for 6022BE (eventually all record lengths are converted into 10K by hack #59; however disabling 'Roll' option is not so easy)
```
// For now - we go for the 10240 size sampling - the other seems not to be
// supported
// Find highest samplerate using less than 10240 samples to obtain our
// duration.
// Better add some margin for our SW trigger
```
3) Cherry-picked items 2 & 3 from #70 (closed).
Screenshots:
FIFO overflow and wrong timebase display
Fix in place

Improved 6022BE stability + timebase display fix

---

openhantek/src/dockwindows.cpp
openhantek/src/openhantek.cpp
openhantek/src/openhantek.h
openhantek/src/settings.cpp
openhantek/src/settings.h

The main window geometry and docking windows / toolbars layout are stored into new [window] section of .ini file. This PR addresses Issue #85.
Screenshot (1020x570)
Please also notice the vertical "File" toolbar on the left-hand side and floating toolbars above Voltage / Spectrum / Trigger tabs.

Load / save states of docking windows and toolbars

---

CMakeLists.txt
openhantek/CMakeLists.txt
openhantek/src/configdialog/DsoConfigColorsPage.cpp
openhantek/src/configdialog/DsoConfigFilesPage.cpp
openhantek/src/dsowidget.cpp
openhantek/src/exporter.cpp
openhantek/src/glscope.cpp
openhantek/src/hantek/hantekdsocontrol.cpp
openhantek/src/hantek/hantekdsocontrol.h
openhantek/src/hantek/usb/usbdevice.cpp
openhantek/src/hantek/usb/usbdevice.h
openhantek/src/main.cpp
openhantek/src/mainwindow.cpp
openhantek/src/mainwindow.h
openhantek/src/scopesettings.h
openhantek/src/settings.cpp
openhantek/src/settings.h
openhantek/src/viewconstants.h
openhantek/src/viewsettings.h

Settings:
* Create settings object in main.cpp already
* Reduce code in settings.h/cpp by using c++11 class field initalisations
* Remove unnessesary color class
* Use a permanent QSettings object and introduce a setFilename method.
Bigger scope:
MainWindow was responsible to create all kind of important objects like the
DataAnalyser, the DSOControl and also the settings object. Finally it is
only responsible for assembling the main graphical interface window and
all DSO related objects are created in main. This way the current GUI can
be more easily replaced with a modern or even headless variant.

Settings refactored. MainWindow with less slots. Autoselect usb devive if only one.

---

openhantek/src/hantek/hantekdsocontrol.cpp
openhantek/src/hantek/hantekdsocontrol.h
openhantek/src/hantek/stateStructs.h
openhantek/src/hantek/usb/usbdevice.cpp
openhantek/src/hantek/usb/usbdevice.h

* Remove usbdevice special case for the 6022 model and introduce a feature flag instead.
* Remove all specific model checks across the hantekdsocontrol class and introduce feature flags instead.
Bigger picture: All model differences should be described in the controlsettings and specification structures
within the constructor of hantekdsocontrol. The rest of the class should be model independant code or marked as
very model dependant code. This should allow to split the class into smaller parts to realize Separation of concerns.
TODO: getSamples() has basically two code paths: One for the 6022Bx and one for all other devices.
I suggest getSamples() and getSamples6022Bx() for instance.

Concentrate model implementation differences to hantekdsocontrol class

---

.travis.yml
CMakeLists.txt
firmware/CMakeLists.txt
firmware/Makefile
firmware/fwget.sh
openhantek/CMakeLists.txt
openhantek/src/analyse/dataanalyzer.cpp
openhantek/src/analyse/dataanalyzer.h
openhantek/src/analyse/dataanalyzerresult.cpp
openhantek/src/analyse/dataanalyzerresult.h
openhantek/src/docks/HorizontalDock.cpp
openhantek/src/docks/HorizontalDock.h
openhantek/src/hantek/definitions.h
openhantek/src/hantek/hantekdsocontrol.cpp
openhantek/src/hantek/hantekdsocontrol.h
openhantek/src/hantek/stateStructs.h
openhantek/src/hantek/usb/usbdevice.cpp
openhantek/src/hantek/usb/usbdevice.h
openhantek/src/main.cpp
openhantek/src/mainwindow.cpp
openhantek/src/scopesettings.h
readme.md

* Minimum Qt version is Qt5.4 now (10th Dec 2014)
* Move fft window pointer from dataanalyzerresult to dataanalyzer. Use smart pointers for all in-between allocations
* Use QSignalBlocker instead of boolean flags in HorizontalDock
* Fix some int signess warnings
* usbdevice: Use if/else instead of switch for getPacketSize and fail with a std::runtime_error if result is unexpected
* hantekdsocontrol: Modernize and make it more readable. Use const on all get methods. Use error enum consistently

Hantekdsocontrol

---

openhantek/src/docks/VoltageDock.cpp
openhantek/src/docks/VoltageDock.h
openhantek/src/glgenerator.cpp
openhantek/src/scopesettings.h

Seems I cannot update or reopen my closed pull request (#67), so here we go, rebased onto current master. The clang-format changes are in a separate commit, which I can squash if you want (there were many other formatting changes, but I only included the one relevant for this pull request).
I currently cannot test the rebased changes as I don't have a scope with me and the new version won't let me start the program if there is no scope.

Add checkbox to display inverted channels, take 2

---

openhantek/src/dsowidget.cpp
openhantek/src/hantek/hantekdsocontrol.cpp
openhantek/src/main.cpp
openhantek/src/settings.cpp
openhantek/src/settings.h
openhantek/src/widgets/levelslider.cpp

@davidgraeff thanks for the great Xmas refactoring!
- The settings loader, however, overrides color settings with default values - the ctor calls **load()** before **setChannelCount()**. Now fixed.
- An extra minor enhancement is new shape of LevelSlider, see screenshot below. Simplifies dragging trigger level & position sliders.
- Finally, the PR eliminates g++ warning 
```
/home/travis/build/OpenHantek/openhantek/openhantek/src/hantek/hantekdsocontrol.cpp: In constructor ‘HantekDsoControl::HantekDsoControl(USBDevice*)’:
/home/travis/build/OpenHantek/openhantek/openhantek/src/hantek/hantekdsocontrol.cpp:223:9: warning: attributes at the beginning of statement are ignored [-Wattributes]
[[clang::fallthrough]];
^
```

Fix settings loader, change LevelSlider needle shape

---

openhantek/src/scopesettings.h
openhantek/src/settings.cpp
openhantek/src/settings.h
openhantek/src/widgets/levelslider.cpp

- Screen & print colors are stored in hex ARGB format (accepted by loader), easy to tweak by hand;
- As agreed before, **setChannelCount()** removed from **DsoSettings**;
- Fixed inverted channel init and load/save.

Enhance settings load/save

---

openhantek/src/glgenerator.cpp
openhantek/src/glgenerator.h
openhantek/src/glscope.cpp
openhantek/src/glscope.h

Fix digital phosphor effect

---

openhantek/src/docks/dockwindows.cpp
openhantek/src/dsowidget.cpp
openhantek/src/selectdevice/selectsupporteddevice.cpp
openhantek/src/utils/printutils.cpp
openhantek/src/widgets/levelslider.cpp

- Bugfix: Show "needle" in trigger position/level sliders, fix regression introduced by 0fb7e43.
- Bugfix: valueToString() fails to display negative values. Later on I'm planning an enhancement which shows marker 1/2 values in DsoWidget (relative to trigger position).
- Enhancement: marker position granularity is now 1% of DIVS_TIME, trigger level is 5% of full scale.

Slider granularity enhancement, trigger level & position slider view fix

---

openhantek/src/dsowidget.cpp
openhantek/src/exporter.cpp
openhantek/src/exporter.h
openhantek/src/glscope.cpp
openhantek/src/glscope.h

- **Marker enhancements.** The user can move marker by mouse drag in the scope area. If left mouse button is pressed close to an existing marker (+/- 1% of horizontal axis), the marker is selected for dragging. Mouse press outside snap area will move Marker 1 to that position, mouse release will set Marker 2.
- Marker positions relative to trigger are displayed in the info label area. Not yet in print / PDF export; those require deep refactoring to show channel offsets, trigger position & level, etc. etc.
Normal view, Marker 1 has positive offset against trigger, Marker 2 has negative offset:
Zoom view:
- **BUGFIX** unsigned int is not good if the loop counts down to 0. Transition to ChannelID everywhere in the code broke exporter.

drag markers by mouse press in the scope area

---

openhantek/src/dsowidget.cpp
openhantek/src/dsowidget.h
openhantek/src/widgets/levelslider.cpp

Channel offset, trigger level and trigger position sliders are attached to zoom view. First two slider sets behave as active mirrors of respective main sliders; any slider position change is immediately applied to its mirror. The trigger position slider in the zoom view is inactive, it reflects relative position of the trigger within zoom window.
Further enhancement could be adding 3rd view to DsoWidget:
- main scope & sliders only
- split view (the one we have now), both main and zoomed scopes are displayed
- zoom view (the new one), main scope & sliders are hidden.

Add sliders to the zoom view

---

openhantek/src/configdialog/DsoConfigScopePage.cpp
openhantek/src/configdialog/DsoConfigScopePage.h
openhantek/src/glscope.cpp
openhantek/src/main.cpp

We need to set a multisampling value at the beginning. Remove antialiasing from config dialog therefore.

OpenGL3/ES does not have anti-aliasing hints as before. 

---

openhantek/src/dsowidget.cpp
openhantek/src/dsowidget.h
openhantek/src/glscope.cpp
openhantek/src/glscope.h
openhantek/src/main.cpp
openhantek/src/scopesettings.h
openhantek/src/widgets/levelslider.cpp
openhantek/src/widgets/levelslider.h

Fix:
* Move all GL startup calls to GLScope::fixOpenGLversion
* Depending on OpenGL or ES availability initialize the QSurfaceFormat
* Don't crash if the shader compilation failed. Show a nice message instead.
* Use DsoWidget::showEvent to update all kind of UI things. Otherwise 
for example the zoom view potentially will be "shown" (setVisible), before the DsoWidget
finished its constructor and we get multiple `initializeGL()` calls.
Optimize:
* Don't write the markers to the GPU each frame update, only
do this if they actually changed position.
Code style:
* LevelSlider: Don't return a value for set* Methods.
* Don't rely on the LevelSliders step to calculate the marker position in the OpenGL view.
Fixes #154 
Fixes #155

Use OpenGL 3.2 instead of 3.3 to make MacOSX work again

---

openhantek/src/selectdevice/selectsupporteddevice.ui

When no device is found, a bit more text is shown,
so make space for that.

Fix device selection dialog size.

---

openhantek/src/hantekdso/modelregistry.cpp
openhantek/src/hantekdso/modelregistry.h

Fixes a segfault on startup. The previous code assumed that ModelRegistry::instance would be initialized before being used by other static initializers.
However, static initialization order is undefined.
Plus, at least unter C++11 and according to 6.7[stmt.decl] p.4, this initialization of get():inst is thread-safe.
(this might be relevant to https://github.com/OpenHantek/openhantek/issues/182)

Segfault on startup fix, #182 related

---

openhantek/src/docks/HorizontalDock.cpp
openhantek/src/hantekdso/hantekdsocontrol.cpp
openhantek/src/post/ppresult.cpp
openhantek/src/settings.cpp
openhantek/src/widgets/sispinbox.cpp

Bugfix (#183) - both issues got addressed. 
Bundle of enhancements:
- made timebase -> samplerate mapping less aggressive, at least half of data samples are now reserved for SW trigger algorithm
- limited 6022BE/BL timebase spinbox range to 10 ns (10e-9 * 48e6 = __0.48 S/div__) ... 10 ms (in fact, 4 ms/div is the longest timebase accepted by SW trigger)
- fixed minor issue: math channel mode is not loaded from settings and reset to default __CH1+CH2__

fix segfault #183, improve SW trigger stability

---

openhantek/src/usb/ezusb.h

I want add openhantek to official Fedora repo. Incorrect FSF address looks like error during packaging.

Correct license notice to latest version recommended by GNU.

---

docs/build.md

OpenSUSE uses rpm packages but it's not a RHEL derivative, their packages have different names so the current instructions are wrong for OpenSUSE users.
This change fixes the issue.
I've successfully built openhantek on OpenSUSE Tumbleweed and it works with a Hantek 6022BE.
I used the source from the tar.gz distributed on the openhantek "website", **OpenHantek-openhantek-0eff8d4.tar.gz**

added OpenSUSE specific build dependency packages

---

openhantek/src/hantekdso/hantekdsocontrol.cpp
openhantek/src/hantekprotocol/controlStructs.cpp
openhantek/src/hantekprotocol/controlStructs.h

Use actual data returned from the cmdGetLimits.

---

CMakeLists.txt

If simultaneously available legacy GL library and GLVND library cmake should prefer the new one.
More info can be found by run 
cmake --help-policy CMP0072

Set cmake policy CMP0072 to choose OpenGL module

---

openhantek/src/main.cpp

unique_ptr deletes target pointer when variable scope ends.
For variable "device" this is the whole main() function.
So Device is destroyed after main() is finished.
Device descructor is calling libusb_close. According to documentation
no libusb function is allowed to be called after libusb_exit().
Fixes #195

Reset the device pointer before libusb_exit().

---

openhantek/src/hantekdso/hantekdsocontrol.cpp

downsampler == 1 means divide by one => no downsampling, use the base clocks.
On 2250, frequency divider is a 16-bit up-counter. It outputs a pulse on
overflow when enabled and reloads the value which was passed in
the ESETTRIGGERORSAMPLERATE command.
If you enable downsampler with ESETTRIGGERORSAMPLERATE and:
- write 0xffff as a counter (0x10001 - 2), it will divide by 2
- write 0xfffe as a counter (0x10001 - 3), it will divide by 3
....
- write 0x0001 as a counter (0x10001 - 0), it will divide by 65535
- write 0x0000 as a counter (0x10001 - 1), it will divide by 65536
Fixes #81

Fix the [no] downsampler border case for DSO 2250.

---

openhantek/src/widgets/dsowidget.cpp
openhantek/src/widgets/dsowidget.h

Make ChannelWidgets look more like a composite widget and layout
properly. Previously it was a widget which was never added to any layout.
Therefore it had default position (0,0) and size (100, 30) inside
it's parrent (DsoWidget). Whenever a trigger position/level slider was in
the left top corner, it was getting under invisible ChannelWidgets.
It this case it was impossible to get it out from there since all
the mouse events were directed to the ChannelWidgets.

A little bit of refactoring for ChannelWidgets.

---

openhantek/src/scopeview/glmoveresizesnap.cpp

a cmath include is needed for std::abs to resolve the overloading to float (errors on Clang)

Add cmath include for std::abs

---

cmake/copy_qt5_dlls_to_bin_dir.cmake

When building with both Visual Studio 2015 Community Edition and Visual Studio 2017 Community Edition, the directory containing the built .exe file is of the form:
...\build-openhantek-Desktop_Qt_n_n_n_MSVC201[57]_64bit-Default\openhantek
rather than
...\build-openhantek-Desktop_Qt_n_n_n_MSVC201[57]_64bit-Default\openhantek\Debug
or
...\build-openhantek-Desktop_Qt_n_n_n_MSVC201[57]_64bit-Default\openhantek\Release
The final step of the built process (running windeployqt) currently fails and my proposed change fixes this.
I have not been able to test the build process with MSVC compilers earlier than 2015. Openhantek fails to compile on MSVC 2013 Update 3 and later due to the compiler not supporting list initialisation (https://msdn.microsoft.com/en-gb/library/Dn793970.aspx)

Fix to windeployqt step for MSVC builds

---

openhantek/src/docks/HorizontalDock.cpp
openhantek/src/hantekdso/devicesettings.h
openhantek/src/hantekdso/dsocontrol.cpp
openhantek/src/hantekdso/dsocontrol.h
openhantek/src/hantekdso/dsoloop.cpp
openhantek/src/hantekdso/modelspecification.h
openhantek/src/hantekprotocol/controlStructs.cpp
openhantek/src/hantekprotocol/controlStructs.h
openhantek/src/post/graphgenerator.cpp
openhantek/src/scopeview/glscopegraph.cpp
openhantek/src/scopeview/glscopegraph.h
openhantek/src/settings/scopesettings.h

This is probably my last commit on the openhantek2 branch.
I've got it to the stage when I can see the reference signal with
- correct offset
- correct period
- correct amplitude
- correct voltage measurement label at the bottom
- it is possible to change the sample rate and the timebase is calculated correctly
Things which are still broken:
- software gain control is broken (and turned off in this commit)
- with the hardware gain control, the gain dropdown shows Vols per full
scale instead of Volts per 1 div
- hardware gain is not initialized when application is first started
(need to select some other gain to initialize it)
- hardware offset is not initialized when changing the gain level
(need to shift the slider a bit to initialize it)
- trigger offset and position are broken
- axes …

A couple of low-level fixes.

---

openhantek/src/usb/usbdevice.cpp
readme.md

Original commit from 0x8BitStorm: https://github.com/thielj/openhantek/pull/2
He suggests that this a Windows only fix to prevent the libusb driver from crashing.
Tested succesful with a 6022BL on Windows 10 and winusb driver on both devices (VID_04B4&PID_602A / VID_04B5&PID_602A).
This pull request also includes a readme update for the appveyor links.

fix for libusb dereference crash / update appveyor links

---

openhantek/src/widgets/sispinbox.cpp
openhantek/src/widgets/sispinbox.h

this fix set the correct background when you change the style.
without the patch and with Dark mode the text and background are
white; with this patch the text remain white but the background will
be set to dark.
thanks to @gmittone

fix Dark mode background introduced with MacOS 10.14 (mojave)

---

.travis.yml

This commit fixes the travis deployment access denied issue.
Instead of the actual key it uses a variable that needs to be set manually.
Create a token with scope "repo" at:
https://github.com/settings/tokens
Copy the token code and add a environment variable at:
https://travis-ci.org/openhantek/openhantek/settings
GITHUB_TOKEN {token code}

travis: fix release uploading

---

CMakeLists.txt

CMake policy CMP0072 was introduced in CMake version 3.11
Replace with equivalent version for older CMake versions

Possible fix for https://github.com/OpenHantek/openhantek/issues/265
